# Generated by Django 4.2.4 on 2023-09-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('nome_pet', models.CharField(max_length=80, verbose_name='Nome do Pet')),
                ('data', models.DateField(help_text='dd/mm/aaaa', verbose_name='Data')),
                ('turno', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde')], max_length=10, verbose_name='Turno')),
                ('tamanho', models.CharField(choices=[(0, 'Pequeno'), (2, 'Grande'), (1, 'Médio')], max_length=7, verbose_name='Tamanho')),
                ('observacoes', models.TextField(blank=True, max_length=200, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reserva Banho',
                'verbose_name_plural': 'Reservas de Banho',
            },
        ),
    ]
