# Generated by Django 4.2.4 on 2023-09-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='tamanho',
            field=models.CharField(choices=[(2, 'Grande'), (0, 'Pequeno'), (1, 'Médio')], max_length=7, verbose_name='Tamanho'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='turno',
            field=models.CharField(choices=[('tarde', 'Tarde'), ('manha', 'Manhã')], max_length=10, verbose_name='Turno'),
        ),
    ]
