# Generated by Django 4.2.4 on 2023-09-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pet', models.CharField(max_length=80, verbose_name='Nome de Pet')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('dia_reserva', models.DateField()),
                ('observacoes', models.TextField(blank=True, max_length=200, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
