# Generated by Django 4.2.4 on 2023-09-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_reserva'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Formulário de Contato', 'verbose_name_plural': 'Formulários de Contatos'},
        ),
        migrations.AddField(
            model_name='contato',
            name='lido',
            field=models.BooleanField(blank=True, default=False, verbose_name='Lido'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='dia_reserva',
            field=models.DateField(verbose_name='Escolha um dia'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nome_pet',
            field=models.CharField(max_length=80, verbose_name='Nome do Pet'),
        ),
    ]
