# Generated by Django 4.2.4 on 2023-09-25 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_contato_options_contato_lido_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
